general:
  data_path: "../data/data.feather"
  target_path: "../data/target.feather"
  random_state: 290
  eval_metric: "rmse"
  objective_type: "regression"
  test: false
  num_cores: 1

optimise:
  opt_direction: "minimize"
  opt_n_trials: 10

predict:
  num_boost_round: 100
  nfold: 3

plot:
  plot_n_trials: null
  plot_n_importance: 150